name: Publish packages

on:
  push:
    branches:
      - main

jobs:
  publish-packages:
    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install imgpkg
        shell: bash
        run: |
          wget -nv -O- https://github.com/vmware-tanzu/carvel-imgpkg/releases/download/v0.28.0/imgpkg-linux-amd64 > /tmp/imgpkg
          chmod 755 /tmp/imgpkg

      - name: Calculate variables
        run: |
          echo "REPOSITORY_SHA7=${GITHUB_SHA::7}" >>${GITHUB_ENV}

      - name: Build and publish spring-academy-lab
        shell: bash
        run: |
          SHA_ARTIFACT=ghcr.io/${{github.repository}}/spring-academy-lab:sha-${REPOSITORY_SHA7}
          LATEST_ARTIFACT=ghcr.io/${{github.repository}}/spring-academy-lab:latest
          /tmp/imgpkg push -i $SHA_ARTIFACT -f packages/spring-academy-lab --registry-username=${{github.actor}} --registry-password=${{secrets.GITHUB_TOKEN}}
          echo ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io --username ${{github.actor}} --password-stdin
          docker pull $SHA_ARTIFACT
          docker tag $SHA_ARTIFACT $LATEST_ARTIFACT
          docker push $LATEST_ARTIFACT


